PitchIn/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PitchIn.Models;
using PitchIn.Domain.Concrete;
using PitchIn.Domain.Entities;
using PitchIn.Domain.Abstract;
using System.IO;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace PitchIn.Controllers
{
    [Authorize(Roles = "worker")]
    public class WorkerController : Controller
    {
      
        private IJobRepository repository;

        public  WorkerController(IJobRepository repo)
        {
            repository = repo;
        }
        [Authorize]
        public ActionResult SubmitEntry(int id)
        {


            return View();
        }
        [HttpPost]
        public ActionResult SubmitEntry(int id, HttpPostedFileBase file)
        {
         

            //var workerTemp = new AcceptWorker
            //{
            //    IsSubmitted = false,
            //    Job = job
            //};

            //job.AcceptWorkers.Add(workerTemp);


            if (file != null)
            {
                var userId = User.Identity.GetUserId();
                repository.SubmitEntry(id, userId, file);

             return   RedirectToAction("Index", "Home");
                //var job = repository.Jobs.Where(j => j.Job_ID == id).FirstOrDefault();
                //if (job != null)
                //{

                //    using (var db = new ApplicationDbContext())
                //    {
                //        db.AcceptWorkers.Add(new AcceptWorker { UserId = User.Identity.GetUserId(), Job_ID = id });
                //        db.SaveChanges();
                //    }
            

                }
                return View();
        }


        public ActionResult Remove(int jobID)
        {
            var db = new ApplicationDbContext();
            var updateRemove = db.AcceptWorkers.Where(x => x.JobId == jobID).First(); 
            db.AcceptWorkers.Remove(updateRemove);
            db.SaveChanges();
            TempData["Msg"] = "Succesfully removed the work accepted.";
            return RedirectToAction("Accepted", "Job");
        }

        // GET: Worker\
        [HttpGet]
        public ActionResult Index()
        {
            var db = new ApplicationDbContext();
            string _userId = User.Identity.GetUserId();
         
            //var getRecent = 

            TimelineViewModel tmv = new TimelineViewModel();

            //var getRecentSubmission = (from getRecent in repository.AcceptWorkers
            //                           join getRecentPhoto in repository.Photos
            //                           on getRecent.Id equals getRecentPhoto.WorkerEntry_Id
            //                           where getRecent.UserId == _userId
            //                           orderby getRecentPhoto.CreatedOn descending
            //                           select getRecent).FirstOrDefault();

            //var acceptWorkerList = db.AcceptWorkers.Where(x => x.UserId == _userId).FirstOrDefault();
            //var acceptJobList = db.Jobs.Where(j => j.AcceptWorkers.Any(a => a.UserId == _userId)).FirstOrDefault();

            var getRecentSubmission = (from getRecent in db.AcceptWorkers
                                       join getRecentPhoto in db.Photos
                                       on getRecent.Id equals getRecentPhoto.WorkerEntry_Id
                                       where getRecent.UserId == _userId
                                       orderby getRecentPhoto.CreatedOn descending
                                       select getRecent).FirstOrDefault();
            var getTopWorker = (from getTop10 in db.Users
                                orderby getTop10.totalWinnings descending
                                where getTop10.totalWinnings > 0
                                select getTop10).Take(10);

            var firstPrize = (from fPrize in db.Jobs
                              orderby fPrize.PrizeFirst descending
                              where fPrize.WinnerFirst == _userId
                              select fPrize).FirstOrDefault();
            /*db.Jobs.OrderByDescending(x => x.PrizeFirst).FirstOrDefault();*/
            var secPrize = (from sPrize in db.Jobs
                            orderby sPrize.PrizeSecond descending
                            where sPrize.WinnerSecond == _userId
                            select sPrize).FirstOrDefault();

            /*db.Jobs.OrderByDescending(x => x.PrizeSecond).FirstOrDefault();*/
            var thirdPrize = (from tPrize in db.Jobs
                              orderby tPrize.PrizeThird descending
                              where tPrize.WinnerThird == _userId
                              select tPrize).FirstOrDefault();
            /* db.Jobs.OrderByDescending(x => x.PrizeThird).FirstOrDefault();*/


            //if (firstPrize.WinnerFirst != null)
            //{
            //    ViewBag.Win = firstPrize.PrizeFirst;
            //}
            //else if (secPrize.WinnerSecond != null)
            //{
            //    ViewBag.Win = secPrize.PrizeSecond;
            //}

            //else if (thirdPrize.WinnerThird != null)
            //{
            //    ViewBag.Win = thirdPrize.PrizeThird;
            //}

            //var getTopWorker = db.Users.OrderByDescending(x => x.totalWinnings).Take(10);
            tmv.getRecent = getRecentSubmission;
            tmv.getTop10Win = getTopWorker;
            tmv.Job = firstPrize;
            //tmv.AcceptJobViewModel.singleWorker = acceptWorkerList;
            //tmv.AcceptJobViewModel.Job = acceptJobList;
            return View(tmv);

            //var db = new ApplicationDbContext();


            //string _userId = User.Identity.GetUserId();

            ////var acceptList = db.AcceptWorkers.Where(m => m.UserId == _userId).ToList();

            //var acceptJobList = db.Jobs.Where(j => j.AcceptWorkers.Any(a => a.UserId == _userId)).ToList();
            ////Job asdf = new Job { Job_ID }
            ////var jobs = db.Jobs.Where(model => acceptList.Any(a => model.Job_ID.Contains(a));
            //var acceptWorkerList = db.AcceptWorkers.Where(x => x.UserId == _userId).ToList();

            //var acceptJobView = new AcceptJobViewModel();
            //acceptJobView.Jobs = acceptJobList;
            //acceptJobView.AcceptWorker = acceptWorkerList;


            //return View(acceptJobView);
            //return View();
        }

        public ActionResult WorkerDashboard()
        {
            var user = GetUser();
            ViewBag.Credits = user.credits;
            ViewBag.Earnings = user.totalWinnings;
            var db = new ApplicationDbContext();
            string _userId = User.Identity.GetUserId();

          
            TimelineViewModel tmv = new TimelineViewModel();
            

            var getRecentSubmission = (from getRecent in db.AcceptWorkers
                                       join getRecentPhoto in db.Photos
                                       on getRecent.Id equals getRecentPhoto.WorkerEntry_Id
                                       where getRecent.UserId == _userId
                                       orderby getRecentPhoto.CreatedOn descending
                                       select getRecent).FirstOrDefault();
            var getTopWorker = (from getTop10 in db.Users
                                orderby getTop10.totalWinnings descending
                                where getTop10.totalWinnings > 0
                                select getTop10).Take(10);

            var firstPrize = (from fPrize in db.Jobs
                              orderby fPrize.PrizeFirst descending
                              where fPrize.WinnerFirst == _userId
                              select fPrize).FirstOrDefault();
            var secPrize = (from sPrize in db.Jobs
                            orderby sPrize.PrizeSecond descending
                            where sPrize.WinnerSecond == _userId
                            select sPrize).FirstOrDefault();

           
            var thirdPrize = (from tPrize in db.Jobs
                              orderby tPrize.PrizeThird descending
                              where tPrize.WinnerThird == _userId
                              select tPrize).FirstOrDefault();
        


           
            tmv.getRecent = getRecentSubmission;
            tmv.getTop10Win = getTopWorker;
            tmv.Job = firstPrize;
         
            return View(tmv);
        }
        public ViewResult OpenChallenges()
        {
            #region Timelineview Model Required!
            //TimelineViewModel Required!!!
            var user = GetUser();
            Session["Credits"] = user.credits;
            ViewBag.Credits = user.credits;
            var userId = User.Identity.GetUserId();
            var userJobs = repository.Jobs.Where(j => j.UserId == userId);

            var model = new TimelineViewModel();
            model.Jobs = userJobs;
            //---------
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser _user = userManager.FindByNameAsync(User.Identity.Name).Result;


            model.User = _user;


            //----------------- end here
            #endregion



            ViewBag.clientCredits = userManager.FindById(User.Identity.GetUserId()).credits;
            var userID = User.Identity.GetUserId();
            //var db = new ApplicationDbContext();
            //var jobs = db.Jobs.ToList()
            //var jobs = repository.Jobs.ToList();

            var x = repository.GetOpenJobs();
            var jobList = x.ToList();
           
            HashSet<int> writerIds = new HashSet<int>(repository.AcceptWorkers.Where( s=> s.UserId== userID).Select(s => s.JobId));

PitchIn/Views/Worker/Index.cshtml
@using Microsoft.AspNet.Identity
@model PitchIn.Models.TimelineViewModel
@*@model PitchIn.Models.AcceptJobViewModel*@
@{
    ViewBag.Title = "Index";
}

<div class="banner">
    @Html.ActionLink("Find a Work", "OpenChallenges", "Worker", null, new { @class = "buttonProject" })
    @*<input type="button" onclick="location.href='@Url.Action("Create New", "Create", "Job")'" class="buttonProject" value="Create Project" style="float: left; margin: 350px 0px 0px 525px" />*@
</div>

<div class="container-timeline pull-left">
    <h3 class="h3Header">Recent Open Challenges</h3>
    <ul class="col-lg-8 col-md-4 col-sm-2 col-xs-12 pull-right infinite-scroll">
        @*@Html.Partial("_JobsRow", (ViewBag.Customers as Dictionary<int, Job>))*@

    </ul>
    @*@Html.Partial("_Loading")*@

</div>
@*</div>*@<!-- end of loop-->

<div class="topPeopleDiv">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">TOP CLIENT</h3>

        </div>
        <div class="panel-body">
            TOP CLIENT
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">TOP DEV</h3>

        </div>
        <div class="panel-body">
            TOP DEV
        </div>
    </div>
</div>




@*<div id="myContent_Main">
    <div id="userContent">
        <div class="iconcontainer">
            <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
                <div class="iconbox">
                    <div class="iconbox-icon">
                        <span class="glyphicon glyphicon-file"></span>
                    </div>



                    <div class="featureinfo">
                        <h4 class="text-center">User Dashboard</h4>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti atque, tenetur quam aspernatur corporis at explicabo nulla dolore necessitatibus doloremque exercitationem sequi dolorem architecto perferendis quas aperiam debitis dolor soluta!
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <div id="myTimeline" class="container">
        <div class="row">
            <div class="timeline-centered">

                <article class="timeline-entry">

                    <div class="timeline-entry-inner">

                        <div class="timeline-icon bg-success">
                            <i class="entypo-feather"></i>
                        </div>

                        <div class="timeline-label">
                            <h2>Latest Challenge Accepted </h2>*@
                            @*<p>Challenge title: @Html.DisplayFor(title => title.Job.Name)</p>*@
                            @*@if (Model.getRecent != null)
                            {
                                @Html.ActionLink("View Accepted Challenge", "Details", "Job", new { jobID = Model.getRecent.JobId }, null)
                            }*@

                        @*</div>
                    </div>

                </article>

                <article class="timeline-entry">

                    <div class="timeline-entry-inner">

                        <div class="timeline-icon bg-secondary">
                            <i class="entypo-suitcase"></i>
                        </div>

                        <div class="timeline-label">
                            <h2>Latest Submitted Challenge</h2>

                            @if (Model.getRecent != null)
                            {
                                <p>@Html.ActionLink("View your entry", "Submit", "Job", new { id = Model.getRecent.Id }, null)</p>
                            }

                        </div>
                    </div>

                </article>

                <article class="timeline-entry">

                    <div class="timeline-entry-inner">

                        <div class="timeline-icon bg-secondary">
                            <i class="entypo-suitcase"></i>
                        </div>

                        <div class="timeline-label">
                            <h2>Latest Winning Challenge</h2>
                           @if (ViewBag.Win != null)
                           {
                            <p> You have earned:  @ViewBag.Win </p>
                           }
                       

                        </div>
                    </div>

                </article>


                <article class="timeline-entry begin">

                    <div class="timeline-entry-inner">

                        <div class="timeline-icon" style="-webkit-transform: rotate(-90deg); -moz-transform: rotate(-90deg);">
                            <i class="entypo-flight"></i> +
                        </div>

                    </div>

                </article>

            </div>


        </div>
    </div>


</div>

<div id="rightContent">

    <div id="accountSummary" class="panel panel-default" style="width:280px;">
        <div class="panel-heading libreStatsPanelHeading">
            <div class="panel-title">
                <span>Top 10 Workers (Earnings)</span>
                <a class="fa fa-caret-down pull-right libreStatsPanelHeadingIcon" href="#uniqueVisitor" data-toggle="collapse"></a>
            </div>
        </div>
        <div class="panel-body libreStatsPanelBody collapse in" id="uniqueVisitor">
            <div class="row clearfix libreStatsPanelRow">
                <div class="col-md-8 column libreStatsPanelValueColumn">
                    @foreach (var top10 in Model.getTop10Win)
                    {
                        <p class="libreStatsCount">
                            @Html.DisplayFor(x=> top10.UserName) &nbsp; Earnings: @Html.DisplayFor(x => top10.totalWinnings)
                        </p>
                    }
                </div>
                <div class="col-md-4 column">
                    <span class="pull-right fa fa-user fa-5x libreStatsIcon"></span>
                </div>
            </div>
        </div>
    </div>
</div>*@
    @*<div class="jumbotron">
            <h1>You are now in Worker DashBoard</h1>
        </div>

        <div class="row">


            <div class="col-md-12 margin-top-20">
                <a href="@Url.Action("OpenChallenges","Worker")" class="btn btn btn-primary btn-lg btn-block">
                    <span class="glyphicon glyphicon-edit text-left"> Browse challenges </span>

                </a>
            </div>


            <div class="col-md-12 margin-top-20">
                <a href="@Url.Action("Accepted","Worker")" class="btn btn btn-primary btn-lg btn-block">
                    <span class="glyphicon glyphicon-ok"> View your accepted challenges </span>

                </a>
            </div>


        </div>*@

    @*<link href="~/Content/main.css" rel="stylesheet" />
        <link href="~/Content/bootstrap.css" rel="stylesheet" />
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/jquery-1.10.2.js"></script>
        <div id="sideMenu">
            <div class="col-sm-10">
                <div class="card hovercard">
                    <div class="cardheader">

                    </div>
                    <div class="avatar">
                        <img alt="" src="http://lorempixel.com/100/100/people/9/">
                    </div>
                    <div class="info">
                        <div class="title">
                            @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                        </div>
                        <div class="desc"><a href="@Url.Action("OpenChallenges","Worker")">Browse Challenges</a></div>
                        <div class="desc"><a href="@Url.Action("Accepted","Worker")">Accepted Challenges</a></div>
                        <div class="desc">About 3</div>
                    </div>
                    <div class="bottom">
                        <a class="btn btn-primary btn-twitter btn-sm" href="#">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a class="btn btn-danger btn-sm" rel="publisher"
                           href="#">
                            <i class="fa fa-google-plus"></i>
                        </a>
                        <a class="btn btn-primary btn-sm" rel="publisher"
                           href="#">
                            <i class="fa fa-facebook"></i>
                        </a>
                        <a class="btn btn-warning btn-sm" rel="publisher" href="#">
                            <i class="fa fa-behance"></i>
                        </a>

                        <form action='setExpressCheckout' METHOD='POST'>
                            <input type='image' name='submit' src='https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif' border='0' align='top' alt='Check out with PayPal' />
                        </form>

                        <form action="@Url.Action("Charge")" method="POST">


                            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" type="text/javascript"
                                    data-key="pk_test_9btCxOAquczpE3NIPvgUz6NT"
                                    data-image="/Images/IMG_87741.jpg"
                                    data-name="Pitch In"
                                    data-description="5 Credits"
                                    data-currency="USD"
                                    data-amount="5000"></script>
                        </form>
                    </div>
                </div>

            </div>
        </div>

        <div id="myContent">*@

    @*<div id="borderTest">
                <ol class="breadcrumb">
                    Accepted Challenges
                 </ol>
                    <div id="openChallengePanel" align="center" style="padding:30px;">

                        @foreach (var item in Model.AcceptWorker)
                        {
                            <div class="row panel panel-default">
                                <div class="panel-heading">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </div>
                                <div class="panel-body">
                                    Description: &nbsp; @Html.DisplayFor(modelItem => item)
                                    <br />
                                    Date End: &nbsp; @Html.DisplayFor(modelItem => item.Date_End)
                                    <br />
                                    @if (Model.AcceptWorker.Where(x => item.Job_ID == x.Job_ID).FirstOrDefault().IsSubmitted)
                                    {
                                        //  @Html.ActionLink("View your entry", "SubmitEntry", new { id = item.Job_ID })
                                        var accept = Model.AcceptWorker.Where(x => x.Job_ID == item.Job_ID).FirstOrDefault();
                                        //  @Html.ActionLink("View your entry", "Submit", new { id = item.Job_ID }, null);
                                      @Html.ActionLink("View your entry", "Submit","Job", new { id = accept.Id }, null);
                                    }
                                    else
                                    {

                                        // @Html.ActionLink("Submit your entry", "SubmitEntry", new { id = item.Job_ID })
                                        @Html.ActionLink("Submit your entry", "ImageCreate","Job" , new { id = item.Job_ID },null)

                                    }
                                </div>
                            </div>
                        }

                        <a href="#"> <<< Prev, 1 , 2, 3.. Next >>></a>
                    </div>
        </div>*@

    @*</div>*@

PitchIn/Views/Worker/SubmitEntry.cshtml
@model PitchIn.Domain.Entities.WorkerEntry

@{
    ViewBag.Title = "SubmitEntry";
}

<h2>SubmitEntry</h2>


@using (Html.BeginForm("SubmitEntry", "Worker", FormMethod.Post,
                                     new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div id="myContent_Main">
        <div id="submissionArea" class="row">
            <hr />
            <form class="form-horizontal form-group">
                <fieldset>


                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @*<div class="control-group">
                            <label class="control-label" for="title">Title</label>
                            <div class="controls">
                                <input id="title" name="title" type="text" placeholder="Name" class="input-xlarge" />

                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="Description">Description</label>
                            <div class="controls">
                                <textarea id="Description" cols="90" rows="2" name="Description">Description</textarea>
                            </div>
                        </div>*@

                    <div class="form-group">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">

                            @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input id="file" name="file" class="input-file" type="file" />
                            <br />
                            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Upload" class="btn btn-info" />

                        </div>
                    </div>
                    @*<div class="control-group">
                            <label class="control-label" for="filebutton">File</label>
                            <div class="controls">
                                <input id="filebutton" name="filebutton" class="input-file" type="file" />
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="singlebutton"></label>
                            <div class="controls">
                                <button id="singlebutton" name="singlebutton" class="btn btn-info">Upload</button>
                            </div>
                        </div>*@

                </fieldset>
            </form>

        </div>
    </div>
            @*<div class="form-horizontal">
                <h4>WorkerEntry</h4>
                <hr />*@


            @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@



            @*<div class="form-group">
                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                        @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            @*<div class="form-group">
                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                        <input type="file" id="file" name="file" /><br />
                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    </div>
                </div>*@








            @*<div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>*@
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PitchIn/Views/Worker/WorkerDashboard.cshtml
@model PitchIn.Models.TimelineViewModel
@using Microsoft.AspNet.Identity
@using PitchIn.Domain.Entities

@{
    ViewBag.Title = "Worker Dashboard";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dashboard</title>
</head>
<body>
    <div class="dashboardBanner">
        User Dashboard
    </div>
    <div class="container-timeline pull-left" style="height: 550px;">
        <div class="col-lg-8 col-md-4 col-sm-2 col-xs-12 pull-right">
            <div class="panel panel-default fadeLeft" style="border-radius: 0;">
                <div class="panel-heading panel-heading-custom-dashboard" style="padding: 25px;">
                    <i class="fa fa-list" aria-hidden="true"></i>
                    &nbsp;&nbsp;Recent Activities
                </div>

                <div class="panel-body" style="padding: 0px;">
                    <ul class="list-group">
                        @if (Model.getRecent != null)
                        {
                            <li class="list-group-item list-group-item-custom">
                                <div class="pull-left">
                                    Latest Challenge Accepted
                                </div>
                                <p>Challenge title: @Html.DisplayFor(title => title.Job.Name)</p>
                                <div class="pull-right">
                                    <a href="@Url.Action("Details", "Job", new { jobID = Model.getRecent.JobId }, null)" , title="View Details">
                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                    </a>
                                </div>

                            </li>
                            <li class="list-group-item list-group-item-custom">
                                <div class="pull-left">
                                    Latest Submitted Challenge
                                </div>
                                <div class="pull-right">
                                    <a href="@Url.Action("Submit", "Job", new { id = Model.getRecent.Id }, null)" , title="View Submission">
                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                    </a>
                                </div>

                            </li>
                        }
                        else
                        {
                            <li class="list-group-item list-group-item-custom">
                                <div class="pull-left">
                                    No recent activities.
                                </div>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="topPeopleDiv fadeRight">

        <div class="panel panel-primary" style="border-radius:0;">
            <div class="panel-heading" style="border-radius:0;">
                <h3 class="panel-title">Statistics</h3>
            </div>
            <div class="panel-body" style="padding: 25px;">
                <div class="row">
                    Credits: <p class="pull-right">$@ViewBag.credits</p>
                </div>
                <div class="row">
                    Earnings: <p class="pull-right">$@ViewBag.Earnings</p>
                </div>
                <div class="row">
                    <form action="@Url.Action("Charge")" method="POST">
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" type="text/javascript"
                                data-key="pk_test_9btCxOAquczpE3NIPvgUz6NT"
                                data-image="/Images/IMG_87741.jpg"
                                data-name="Pitch In"
                                data-description="5 Credits"
                                data-currency="USD"
                                data-amount="5000"></script>
                    </form>
                </div>
            </div>
        </div>
        <div class="panel panel-primary" style="border-radius:0;">
            <div class="panel-heading" style="border-radius:0;">
                <h3 class="panel-title">Projects</h3>
            </div>
            <div class="panel-body" style="padding: 25px;">
                <div class="row">
                    Active Projects: <p class="pull-right">0.00</p>
                </div>
                <div class="row">
                    Completed Projects: <p class="pull-right">0.00</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>